services:
  postgres:
    image: postgres:18.1
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./docker/postgres:/docker-entrypoint-initdb.d
  
  seq:
    image: datalust/seq:2025.2
    restart: unless-stopped
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "True"
    volumes:
      - seq_data:/data
        
  voxpop-core:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Voxpop.Core/src/Voxpop.Core.Api/Dockerfile
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}

      ConnectionStrings__CoreDb: Host=postgres;Database=core_db;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}

      Jwt__Key: ${JWT_KEY}

      Serilog__WriteTo__1__Args__serverUrl: http://seq:5341

    depends_on:
      postgres:
        condition: service_healthy
      seq:
        condition: service_started
        
  voxpop-identity:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Voxpop.Identity/src/Voxpop.Identity.Api/Dockerfile
    ports:
      - "5002:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}

      ConnectionStrings__IdentityDb: Host=postgres;Database=identity_db;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}

      Jwt__Key: ${JWT_KEY}

      Serilog__WriteTo__1__Args__serverUrl: http://seq:5341
    depends_on:
      postgres:
        condition: service_healthy
      seq:
        condition: service_started

volumes:
  postgres_data:
  seq_data: